### ISSUE TITLE
Roles to be given

### ISSUE THREAD

**Issue by OckerOCE** [furyaus/rankbot#2]
Roles that need to be assigned.

KDA
- 1 KD, + 1 KD, + 1.5 KD, + 2 KD, + 2.5 KD, + 3 KD, + 3.5 KD, + 4 KD

ADR
+ 100 ADR, + 150 ADR, + 200 ADR, + 250 ADR, + 300 ADR, + 350 ADR, + 400 ADR

RANK
Bronze, Silver, Gold, Platinum, Diamond, Master

Top Ranks
Terminator for the Top KDA
Punnisher for the Top ADR
General for the Top Rank

**Comment by furyaus** [comment]
I am thinking we shouldnt assign KDA and ADR - these will be displayed in the KDA and ADR leader boards and its a little non-inclusive to have KDA and ADR as a role on your user. Ranks are done, implementing General now.

**Comment by furyaus** [comment]
All done, general is implemented on highest current rank points
